version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s'
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'

handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file:
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: logs/nostr_simulator.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    level: ERROR
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  nostr_simulator:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

  nostr_simulator.simulation:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  nostr_simulator.agents:
    level: DEBUG
    handlers: [console, file]
    propagate: false

root:
  level: WARNING
  handlers: [console]
